# ===================================================================================================
# Configuración Spring Boot - CLOUD
#
# Configuración para el profile de Spring "cloud".
# Aquí se establece la configuración para la aplicación que se
# ejecuta en Bluemix, independientemente del ambiente (dev, test, prod)
# ===================================================================================================

# ===================================================================================================
# Propiedades estandar de Spring.
# Referencia completa en:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================================================

spring:
  profiles:
    active: cloud
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  jpa:
    show-sql: false


openpay:
  wsdlLocation: openpay.wsdl
  header:
    api:
      name: X-Id
      key: 12345

estadocuenta:
  wsdlLocation: estadocuenta.wsdl
  header:
    api:
      name: X-Id
      key: 12345
  ruta: c:\Automata SMV\CIE por Convenio\
  nombre: CLCO{CUENTA}yyMMddHHmm.txt
    