# ===================================================================================================
# Configuración Spring Boot - PRINCIPAL
#
# Configuración base de la aplicación, actúa en conjunto con el application-PROFILE.yml.
# Aquí se establece la configuración base que normalmente no debería cambiar de acuerdo al
# profile, o que podría aplicar para más de un profile.
# ===================================================================================================

# ===================================================================================================
# Propiedades estandar de Spring.
# Referencia completa en:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================================================

management:
  context-path: /mimonte
security:
  ignored: /,/index.html,/favicon.png,/logo.png,

info:
  project:
    version: 0.0.1

spring:
  application:
    name: Micro Servicios Pagos Mi Monte
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
# Variables utiles para app microservicios mimonte
#Pagos
mimonte:
  variables:
    actividades-max-default: 10
    estatus-varios:
      no-identificada: "No identificada en MIDAS"
    mail:
      solicitud-pagos:
        title: "Solicitud de Pagos"
        encode-type: UTF-8
        velocity-layout: mailHtml.vm
      text1: "Buenas tardes."
      text2: "Solicito de su apreciable ayuda para aplicar los siguientes pagos a las partidas especificadas en la siguiente tabla en el barrido de la noche,  ya que el cliente realizo el pago en el portal de pago en línea, el cual fue aprobado, pero en Midas aún no se refleja el cobro."
      text3: "En espera de sus comentarios y apreciable ayuda. Gracias."
      table:
        headers:
          fechaTransaccion: "Fecha de la Transacción"
          folioPartida: "Folio Partida"
          transaccion: "Transacción"
          codigoDescuento: "Código de Descuento"
          tipoTransaccion: "Tipo de Transacción"
          montoTransaccion: "Monto de la Transacción"
          tipoMoneda: "Tipo de Moneda"
          tipoCuenta: "Tipo de Cuenta"
          codigoRespuestaMotorPagosTransaccion: "Código de Respuesta de Motor de Pagos de Transacción"
          metodoPago: "Método de Pago"
          identificadorCuenta: "Identificador de Cuenta"
          idTerminalAdquiriente: "Id de Terminal de Adquiriente"
          titularCuenta: "Titular de la Cuenta"
          codigoAutorizacion: "Código de Autorización"
          codigoRespuestaAdquiriente: "Código de Respuesta de Adquiriente"
          numeroLoteAdquiriente: "Número de Lote de Adquiriente"
          fuenteTransaccion: "Fuente de Transacción"
      response:
          resp-key: respuesta
          cod-key: codigo
      from: mail@nmp.com
      auth:
        user: mimonte
        password: iXjqY2ccS783PTF0
      common-headers:
        auth: Authorization
        auth-value: Basic
        content-type: Content-Type
        id-consumidor: idConsumidor
        id-consumidor-value: 42
        id-destino: idDestino
        id-destino-value: 100
        usuario: usuario
        usuario-value: usuario
      token:
        headers:
          grant-key: grant_type
          grant-value: client_credentials
          scope-key: scope
          scope-value: UserProfile.me
          content-type-value: application/x-www-form-urlencoded
        url: https://iamdr.montepiedad.com.mx:4444/NMP/oauth2/v1
      send-mail:
        success-flag: success
        headers:
          oauth-bearer-key: oauth.bearer
          content-type-value: application/json
        url: https://iamdr.montepiedad.com.mx:4444/NMP/Utileria/EnvioCorreo/v2
      solicitudDevolucion:
        title: "Solicitud de Devoluciones"
        velocityTemplate: solicitudDevoluciones.vm
        bodyText1: "Buena tarde."
        bodyText2: "Por favor nos apoyan a realizar las siguientes devoluciones al cliente, así mismo se autoriza el cargo bancario a la cuenta ${numeroCuenta} con la afiliación ${afiliacion}"
    restTemplate:
      maxAttempt: 3
      retryTimeInterval: 3000
    consultaEstadoCuenta:
      url: https://iamdr.montepiedad.com.mx:4444/NMP/GestionFinanzas/Conciliacion/DocEdoCuenta/v1
      auth:
        usuario: mimonte
        password: iXjqY2ccS783PTF0
      header:
        usuario: usuario
        idConsumidor: 42
        idDestino: 100
    cantidad-maxima-tarjetas: 3
    cantidad-maxima-partidas: 10
    iva: 0.16
    dss:
      idcliente: "{idCliente}"

openpay:
  wsdlLocation: openpay.wsdl
  header:
    api:
      name: X-Id
      key: 12345

estadocuenta:
  ruta: "'/'ddMMyy"
  nombre: "'CLCO{CUENTA}'yyMMdd'.txt'"
