# ===================================================================================================
# Configuración Spring Boot - CLOUD
#
# Configuración para el profile de Spring "cloud".
# Aquí se establece la configuración para la aplicación que se
# ejecuta en Bluemix, independientemente del ambiente (dev, test, prod)
# ===================================================================================================

# ===================================================================================================
# Propiedades estandar de Spring.
# Referencia completa en:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================================================

spring:
  profiles:
    active: cloud
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  jpa:
    show-sql: false

logback:
  loglevel: INFO

# Variables utiles para app microservicios mimonte
#Pagos
mimonte:
  variables:
    mail:
      solicitud-pagos:
        title: "Solicitud de Pagos"
        velocity-layout: "/templates/mailHtml.vm"
        text1: "Buenas tardes."
        text2: "Solicito de su apreciable ayuda para aplicar los siguientes pagos a las partidas especificadas en la siguiente tabla en el barrido de la noche,  ya que el cliente realizó el pago en el portal de pago en línea, el cual fue aprobado, pero en Midas aún no se refleja el cobro."
        text3: "En espera de sus comentarios y apreciable ayuda. Gracias."
      solicitudDevolucion:
        title: "Solicitud de Devoluciones"
        velocityTemplate: "/templates/solicitudDevoluciones.vm"
        bodyText1: "Buena tarde."
        bodyText2: "Por favor nos apoyan a realizar las siguientes devoluciones al cliente, así mismo se autoriza el cargo bancario en la entidad ${entidad}, a la cuenta ${numeroCuenta}"
#        bodyText2: "Por favor nos apoyan a realizar las siguientes devoluciones al cliente, así mismo se autoriza el cargo bancario a la cuenta ${numeroCuenta} con la afiliación ${afiliacion}"
      from: mail@nmp.com
      auth:
        user: mimonte
        password: iXjqY2ccS783PTF0
      common-headers:
        id-consumidor: idConsumidor
        id-consumidor-value: 42
        id-destino: idDestino
        id-destino-value: 100
        usuario: usuario
        usuario-value: usuario
      token:
        url: https://iamdr.montepiedad.com.mx:4444/NMP/oauth2/v1
      send-mail:
        url: https://iamdr.montepiedad.com.mx:4444/NMP/Utileria/EnvioCorreo/v2
    consultaEstadoCuenta:
      url: https://iamdr.montepiedad.com.mx:4444/NMP/GestionFinanzas/Conciliacion/DocEdoCuenta/v1
      auth:
        usuario: mimonte
        password: iXjqY2ccS783PTF0
      header:
        usuario: usuario
        idConsumidor: 42
        idDestino: 100
      archivo:
        ruta: "'/Extractos/MovimientosHistoricosC43/'ddMMyy"
        nombre: "'MH43{CUENTA}'yyMMdd'0700.txt'"
    consultaPagos:
      url: https://dev1775oxxo-midasms-pagos-midas.mybluemix.net/nmp/pagos/v1/consultaPago
    dss:
      idcliente: "{idCliente}"
    restTemplate:
      maxAttempt: 3
      retryTimeInterval: 3000
    actividades-max-default: 10
    cantidad-maxima-tarjetas: 3
    cantidad-maxima-partidas: 10
    iva: 0.16
