# ===================================================================================================
# Configuración Spring Boot - DEV
#
# Configuración para el profile de Spring "dev".
# Aquí se establece la configuración necesaria para el perfil de ejecución local con
# base de datos también local
# ===================================================================================================

# ===================================================================================================
# Propiedades estandar de Spring.
# Referencia completa en:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================================================


server:
  port: 8080

spring:
  profiles:
    active: dev
    include: swagger
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://sl-us-south-1-portal.50.dblayer.com:19239/compose?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: admin
    password: TAAEHZZUXVCVXVVY
    testWhileIdle: true
    validationQuery: SELECT 1
    tomcat:
      max-active: 1
    driver-class-name: com.mysql.jdbc.Driver

  batch:
    job:
      enabled: false

# Variables utiles para app microservicios mimonte
mimonte:
  variables:
    mail:
      solicitud-pagos:
        title: "Solicitud de Pagos"
        encode-type: UTF-8
        velocity-layout: mailHtml.vm
      text1: "Buenas tardes."
      text2: "Solicito de su apreciable ayuda para aplicar los siguientes pagos a las partidas especificadas en la siguiente tabla en el barrido de la noche,  ya que el cliente realizo el pago en el portal de pago en línea, el cual fue aprobado, pero en Midas aún no se refleja el cobro."
      text3: "En espera de sus comentarios y apreciable ayuda. Gracias."
      table:
        headers:
          fechaTransaccion: "Fecha de la Transacción"
          folioPartida: "Folio Partida"
          transaccion: "Transacción"
          codigoDescuento: "Código de Descuento"
          tipoTransaccion: "Tipo de Transacción"
          montoTransaccion: "Monto de la Transacción"
          tipoMoneda: "Tipo de Moneda"
          tipoCuenta: "Tipo de Cuenta"
          codigoRespuestaMotorPagosTransaccion: "Código de Respuesta de Motor de Pagos de Transacción"
          metodoPago: "Método de Pago"
          identificadorCuenta: "Identificador de Cuenta"
          idTerminalAdquiriente: "Id de Terminal de Adquiriente"
          titularCuenta: "Titular de la Cuenta"
          codigoAutorizacion: "Código de Autorización"
          codigoRespuestaAdquiriente: "Código de Respuesta de Adquiriente"
          numeroLoteAdquiriente: "Número de Lote de Adquiriente"
          fuenteTransaccion: "Fuente de Transacción"
      response:
        resp-key: respuesta
        cod-key: codigo
      from: mail@nmp.com
      auth:
        user: mimonte
        password: iXjqY2ccS783PTF0
      common-headers:
        auth: Authorization
        auth-value: Basic
        content-type: Content-Type
        id-consumidor: idConsumidor
        id-consumidor-value: 42
        id-destino: idDestino
        id-destino-value: 100
        usuario: usuario
        usuario-value: usuario
      token:
        headers:
          grant-key: grant_type
          grant-value: client_credentials
          scope-key: scope
          scope-value: UserProfile.me
          content-type-value: application/x-www-form-urlencoded
        url: https://iamdr.montepiedad.com.mx:4444/NMP/oauth2/v1
      send-mail:
        success-flag: success
        headers:
          oauth-bearer-key: oauth.bearer
          content-type-value: application/json
        url: https://iamdr.montepiedad.com.mx:4444/NMP/Utileria/EnvioCorreo/v2
    cantidad-maxima-tarjetas: 3
    iva: 0.16
    dss:
      idcliente: "{idCliente}"
      idregla: "{idRegla}"
      idafiliacionregla: "{idAfiliacionRegla}"
      idtipo: "{idTipo}"

servicios:


openpay:
  wsdlLocation: openpay.wsdl
  header:
    api:
      name: X-Id
      key: 12345

estadocuenta:
  wsdlLocation: estadocuenta.wsdl
  header:
    api:
      name: X-Id
      key: 12345
  ruta: c:\Automata SMV\CIE por Convenio\
  nombre: "'CLCO{CUENTA}'yyMMddHHmm'.txt'"
